version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9-stretch-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd web-connect docker build -t web-connect . docker run --rm --name web -p 8080:8080 web-connect
